version: "3.7"

services:
    sql:
        image: postgres:13-alpine
        env_file: 
            - .env
        volumes:
            - pg-data:/var/lib/postgresql/data
    web:
        build: .
        image: cowry-alpine
        env_file:
            - .env
        ports:
            - "8080:8080"
        depends_on:
            - sql

volumes:
    pg-data:
